// <auto-generated />
using Ef7JsonColumns.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ef7JsonColumns.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221014202550_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ef7JsonColumns.SuperHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Ef7JsonColumns.SuperHero", b =>
                {
                    b.OwnsOne("Ef7JsonColumns.HeroDetails", "Details", b1 =>
                        {
                            b1.Property<int>("SuperHeroId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SuperHeroId");

                            b1.ToTable("Heroes");

                            b1.ToJson("Details");

                            b1.WithOwner()
                                .HasForeignKey("SuperHeroId");
                        });

                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
